config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'home#about'

  root "home#top"

  get 'search' => 'searches#search'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users

  resources :books do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :create, :update, :show, :edit]

  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :books
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/plofile_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  attachment :profile_image

  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length: { maximum: 50 }

  def self.search(search,word)
		if search == "forward_match"
			@user = User.where("name LIKE?","#{word}%")
		elsif search == "backward_match"
			@user = User.where("name LIKE?","%#{word}")
		elsif search == "perfect_match"
			@user = User.where("#{word}")
		elsif search == "partial_match"
			@user = User.where("name LIKE?","%#{word}%")
		else
			@user = User.all
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, only: [:edit, :update, :destroy]

	def home
	end

	def create
		@books = Book.all
		@book = Book.new
		@user = current_user
		@book.user_id = current_user.id
		if @book.save
			redirect_to book_path(@book.id), notice:"successfully"
		else
			flash[:error] = "error"
			render "index"
    	end
	end

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	def show
		@books = Book.new
		@book = Book.find(params[:id])
		@users = User.all
		@user = @book.user
		@book_comment = BookComment.new
    @book_comments = @book.book_comments
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user.id != current_user.id
			redirect_to books_path
		else
			render "edit"
		end
	end

	def update
		@book = Book.find(params[:id])
    	if @book.update(book_params)
    		redirect_to book_path(@book.id), notice: "successfully"
		else
			flash[:error] = "error"
			render "edit"
      	end
	end

	def destroy
		@book = Book.find(params[:id])
  		@book.destroy
 		redirect_to books_path
	end

	private

	def book_params
		params.require(:book).permit(:title, :body)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationControlle
  def search
    @range = params[:range]
    search = params[:search]
    word = params[:word]
    if @range == '1'
      @user = User.search(search,word)
    else
      @book = Book.search(search,word)
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.all
		@book = Book.new
		@user = current_user
	end


	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
    		redirect_to user_path(@user.id), notice: "successfully"
		else
			flash[:error] = "error"
			render "edit"
      	end
	end

	def show
		@user = User.find(params[:id])
		@books = @user.books
		@book = Book.new
	end

	def edit
		@user = current_user
		@book = Book.new
		@users = User.find(params[:id])
		if @users.id != @user.id
			redirect_to user_path(@user.id)
		else
			render "edit"
		end
	end

	private
	def user_params
  	params.require(:user).permit(:name, :profile_image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newbook.html.erb
<h2>New book</h2>
    <% if book.errors.any? %>
      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message+"error" %></li>
        <% end %>
      </ul>
    <% end %>
    
    <%= form_for(book) do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Opinion</h4>
      <%= f.text_area :body %>

      <div><%= f.submit 'Create Book' ,class:"btn btn-primary col-xs-12"%></div>
    <% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
	<% if @book.errors.any? %>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message+"error" %></li>
        <% end %>
      </ul>
    <% end %>

	<%= form_for(@book) do |f| %>
		<h4>Title</h4>
		<%= f.text_field :title %>

		<h4>Opinion</h4>
		<%= f.text_field :body %>

		<%= f.submit 'Update Book' %>

		<%=link_to "Show" ,book_path %>
		<%=link_to "Back" ,books_path %>

	<% end %>

app/views/books/home.html.erb
<div class="top-message col-md-offset-3 col-md-6">
	<h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</span></h1>
    <p>
      In  
      <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,<br>
      you can shere and exchange your opinions,and emotions<br>
      about various books!
	</p>

    <div><%= link_to "Log in",new_user_registration_path, class: 'btn btn-info col-xs-10 col-xs-offset-1 sign_in' %></div>
    <div><%= link_to "Sign Up",new_user_registration_path, class: 'btn btn-success col-xs-10 col-xs-offset-1 sign_up' %></div>
</div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">

        <div class="col-xs-3">
          <h2>User info</h2>
            <img class="attachment user profile_image fallback">
              <table class="table">
                <tbody>
                  <tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", size: "100x100"%></tr>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                  <tr>
                    <td>introduction</td>
                    <td><%= @user.introduction %></td>
                  </tr>
                </tbody>
              </table>

    <%= link_to "", edit_user_path(@user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <%= render ‘relationships/follow_button’, user: @user %>
  <%= render 'books/newbook', book: @book %>
</div>

    <div class="col-xs-9">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
    	   <thead>
            <tr>
             <th></th>
             <th>Title</th>
             <th>Opinion</th>
    		    </tr>
    	   </thead>

        <% @books.each do |book| %>
          <tr>
            <div>
              <td><%= link_to (attachment_image_tag book.user,:profile_image, :fill, 60, 60, fallback: "no_image.png", size: "40x40") ,user_path(book.user) %></td>
            </div>
            <div>
              <td></td>
            </div>
            <div>
              <td><%= link_to "#{book.title}" ,book_path(book.id) %></td>
            </div>
            <div>
          	 <td><%= book.body %></td>
            </div>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="body">
  <div class="container">
    <div class="row">

        <div class="col-xs-3">
          <h2>User info</h2>
            <img class="attachment user profile_image fallback">
              <table class="table">
                <tbody>
                  <tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", size: "100x100" %></tr>
                    <tr>
                      <td>name</td>
                      <td><%= @user.name %></td>
                  </tr>
                  <tr>
                    <td>introduction</td>
                    <td><%= @user.introduction %></td>
                  </tr>
                </tbody>
              </table>

    <%= link_to "", edit_user_path(@user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <%= render ‘relationships/follow_button’, user: @user %>
  <h2>New book</h2>
    <% if flash[:notice] %>
      <div class = "flash" >
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= form_for(@books) do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>

      <h4>Opinion</h4>
      <%= f.text_area :body %>

      <div><%= f.submit 'Create Book' ,class:"btn btn-primary col-xs-12"%></div>
    <% end %>
</div>


    <div class="col-xs-9">
      <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
    	   <thead>
    		    <tr>
    			   <th>Title</th><th>Opinion</th>
    		    </tr>
    	   </thead>
          <tr>
            <div>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", size: "100x100" %></td>
            </div>
            <div>
              <td><%= @user.profile_image %></td>
              <td><%= link_to "#{@user.name}" ,user_path(@user) %></td>
            </div>
            <div>
          	 <td><%= @book.title %></td>
            </div>
            <div>
             <td><%= @book.body %></td>
            </div>

            <td>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                <span class="glyphicon glyphicon-heart"><%= @book.favorites.count%></span>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <span class="glyphicon glyphicon-heart-empty"><%= @book.favorites.count %></span>
              <% end %>
            <% end %>
            </td>

            <% if @user.id == current_user.id %>
              <td><%=link_to "Edit" ,edit_book_path(@book.id) ,class: "btn-sm btn-success edit_book_33494" %></td>
              <td><%=link_to "Destroy" ,book_path(@book.id), method: :delete, data: {confirm: "Are you sure?"} ,class: "btn-sm btn-danger destroy_book_33494" %></td>
            <% end %>
          </tr>
      </table>

      <td>コメント数：<%= @book.book_comments.count %></td>

      <% if current_user == @book_comment.user %>
        <td><%= link_to 'Destroy', book_book_comment_path(@book, book_comment), class: 'btn-sm btn-danger', method: :delete %></td>
      <% end %>

      <table>
        <% @book_comments.each do |book_comment| %>
          <tr>
            <td class="show-comment">
            <%= link_to user_path(book_comment.user), class: "user_#{book_comment.user.id}" do %>
            <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "50x50" %><br>
            <%= book_comment.user.name %>
            <% end %>
            </td>
            <td class="show-comment"><%= book_comment.comment %></td>
          </tr>
        <% end %>
      </table>

      <div class="comment-form">
        <%= form_for [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, size: "90x5" %>
          <%= f.submit '送信', class: "btn-sm btn-primary" %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<p id ="notice">
  <%= notice %>
</p>
<h1>User info</h1>
  <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message+"error" %></li>
        <% end %>
      </ul>
    <% end %>

  
    <%= form_for(@user) do |f| %>
      <div class="edit_user">
        <div>Name</div>
        <%= f.text_field :name, autofocus: true, id:"inputEmail", placeholder:"name" %>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
      </div>

      <div class="image">
        <div>Image</div>
      <%= f.attachment_field :profile_image, placeholder: "Image", class: "user-edit-form" %>
      </div>

      <div class="user_introduction">
        <div>Introduction</div>
        <%= f.text_area :introduction, autofocus: true, id:"inputEmail", placeholder:"introduction" %>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
      </div>

      <%= f.submit "Update User" %>

    <% end %>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">

        <div class="col-xs-3">
          <h2>User info</h2>
              <table class="table">
                <tbody>
                  <tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", size: "100x100" %></tr>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                  <tr>
                    <td>introduction</td>
                    <td><%= @user.introduction %></td>
                  </tr>
                </tbody>
              </table>

    <%= link_to "", edit_user_path(@user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

  <%= render 'books/newbook', book: @book %>
</div>


    <div class="col-xs-9">
      <h2>Users</h2>
        <table class="table table-hover table-inverse">
    	   <thead>
    		    <tr>
    			   <th>image</th><th>name</th>
    		    </tr>
    	   </thead>

        <% @users.each do |user| %>
          <tr>
            <div>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.png" %></td>
            </div>
            <div>
          	 <td><%= user.name %></td>
            </div>
            <span>
              <td><%=link_to "Show" ,user_path(user.id) %></td>
            </span>
            <%= render ‘relationships/follow_button’, user: @user %>
          </tr>
        <% end %>
      </table>
    </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id ="notice">
  <%= notice %>
</p>
<div class="body">
  <div class="container">
    <div class="row">

        <div class="col-xs-3">
          <h2>User info</h2>
              <table class="table">
                <tbody>
                  <tr><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", size: "100x100" %></tr>
                  <tr>
                    <td>name</td>
                    <td><%= @user.name %></td>
                  </tr>
                  <tr>
                    <td>introduction</td>
                    <td><%= @user.introduction %></td>
                  </tr>
                </tbody>
              </table>

    <%= link_to "", edit_user_path(@user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    <%= render ‘relationships/follow_button’, user: @user %>
<%= render 'books/newbook', book: @book %>
</div>


    <div class="col-xs-9">
      <h2>Books</h2>
        <table class="table table-hover table-inverse">
    	   <thead>
    		    <tr>
    			   <th>Title</th><th>Opinion</th>
    		    </tr>
    	   </thead>

        <% @books.each do |book| %>
          <tr>
            <div>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", size: "40x40" %></td>
            </div>
            <div>
          	 <td><%=link_to (book.title),book_path(book) %></td>
            </div>
            <div>
             <td><%= book.body %></td>
            </div>
            <span>
            <td><%=link_to "Index" ,book_path(book) %></td>
          </span>
          </tr>
        <% end %>
      </table>
    </div>
    </div>
  </div>
</div>