config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'home#about'

  root "home#top"

  get 'search' => 'searches#search'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users

  resources :books do
    resources :book_comments, only:[:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :create, :update, :show, :edit]

  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :books
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/plofile_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  attachment :profile_image

  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length: { maximum: 50 }

  def self.search(search,word)
		if search == "forward_match"
			@user = User.where("name LIKE?","#{word}%")
		elsif search == "backward_match"
			@user = User.where("name LIKE?","%#{word}")
		elsif search == "perfect_match"
			@user = User.where("#{word}")
		elsif search == "partial_match"
			@user = User.where("name LIKE?","%#{word}%")
		else
			@user = User.all
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, only: [:edit, :update, :destroy]

	def home
	end

	def create
		@books = Book.all
		@book = Book.new
		@user = current_user
		@book.user_id = current_user.id
		if @book.save
			redirect_to book_path(@book.id), notice:"successfully"
		else
			flash[:error] = "error"
			render "index"
    	end
	end

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	def show
		@books = Book.new
		@book = Book.find(params[:id])
		@users = User.all
		@user = @book.user
		@book_comment = BookComment.new
    @book_comments = @book.book_comments
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user.id != current_user.id
			redirect_to books_path
		else
			render "edit"
		end
	end

	def update
		@book = Book.find(params[:id])
    	if @book.update(book_params)
    		redirect_to book_path(@book.id), notice: "successfully"
		else
			flash[:error] = "error"
			render "edit"
      	end
	end

	def destroy
		@book = Book.find(params[:id])
  		@book.destroy
 		redirect_to books_path
	end

	private

	def book_params
		params.require(:book).permit(:title, :body)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.all
		@book = Book.new
		@user = current_user
	end


	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
    		redirect_to user_path(@user.id), notice: "successfully"
		else
			flash[:error] = "error"
			render "edit"
      	end
	end

	def show
		@user = User.find(params[:id])
		@books = @user.books
		@book = Book.new
	end

	def edit
		@user = current_user
		@book = Book.new
		@users = User.find(params[:id])
		if @users.id != @user.id
			redirect_to user_path(@user.id)
		else
			render "edit"
		end
	end

	private
	def user_params
  	params.require(:user).permit(:name, :profile_image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <p class="navbar-brand navbar-reft">Bookers</p>
          <% if user_signed_in? %>
          <%= form_tag(search_path, method: :get) do %>
            <%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']]) %>
            <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
            <%= text_field_tag (:word) %>
            <%= submit_tag "検索" %>
          <% end %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", user_path(current_user.id), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to "Users", users_path, class:'glyphicon glyphicon-user users' %></li>
              <li><%= link_to "Books",books_path, class:'glyphicon glyphicon-book books' %></li>
              <li>

                <%= link_to "logout",destroy_user_session_path, class:'glyphicon glyphicon-log-out logout' %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to " Home", root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to "About",  home_about_path, class:'glyphicon glyphicon-link about' %></li>
              <li>
                  <%= link_to "sign up", new_user_registration_path, class:'glyphicon glyphicon-edit sign_up'%>
              </li>
              <li><%= link_to "login",new_user_session_path,class:'glyphicon glyphicon-log-in sign_in' %></li>
          <% end %>
              </ul>
        </nav>

        <div style="margin-top: 51px">
        <%= yield %>
        </div>

        <footer>
          <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
        </footer>
    </div>
  </body>
</html>